/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppToasts: typeof import('./src/components/AppToasts.vue')['default']
    CreatableSelect: typeof import('./src/components/CreatableSelect.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ItemPicker: typeof import('./src/components/ItemPicker.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
